import '@styles/reset.css'
import '@/styles/globalTheme.css'
import type { Metadata } from 'next'
import ReactQueryProvider from '@/lib/tanstack-query/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
